# Generated by Django 4.2.7 on 2023-12-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Onaylandı', 'Onaylandı'), ('Kaldırıldı', 'Kaldırıldı')], default='Yeni', max_length=10, verbose_name='Durum'),
        ),
    ]
