# Generated by Django 4.2.7 on 2023-12-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productdiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'verbose_name': 'İndirim Ürün', 'verbose_name_plural': 'İndirim Ürünler'},
        ),
    ]
