# Generated by Django 4.2.7 on 2023-12-08 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productdiscount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İndirim'),
        ),
    ]
