# Generated by Django 4.2.7 on 2023-12-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_contact_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'İletişim Formu', 'verbose_name_plural': 'İletişim Formları'},
        ),
    ]
