# Generated by Django 4.2.7 on 2023-11-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Şehir')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Ülke')),
                ('image', models.ImageField(blank=True, upload_to='images/users/', verbose_name='Resim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
