# Generated by Django 4.2.7 on 2023-12-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_favoriteproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'verbose_name': 'Favori Ürün', 'verbose_name_plural': 'Favori Ürünler'},
        ),
    ]
