# Generated by Django 4.2.7 on 2023-12-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'İşleme Alındı'), ('Canceled', 'İptal Edildi')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'İşleme Alındı'), ('Preparing', 'Hazırlanıyor'), ('OnShipping', 'Kargolandı'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], default='New', max_length=10),
        ),
    ]
