# Generated by Django 4.2.7 on 2023-12-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'İşleme Alındı'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], default='New', max_length=10),
        ),
    ]
