# Generated by Django 4.2.7 on 2023-12-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cart_quantity_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'İşleme Alındı'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], default='New', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='Adet'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'İşleme Alındı'), ('Preparing', 'Hazırlanıyor'), ('OnShipping', 'Kargolandı'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], default='New', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='subtotal',
            field=models.FloatField(verbose_name='Toplam'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
    ]
