# Generated by Django 4.2.7 on 2023-12-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_status_alter_orderproduct_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
