# Generated by Django 4.2.7 on 2023-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_create_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Toplam'),
        ),
    ]
