# Generated by Django 4.2.7 on 2023-12-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_total_alter_orderproduct_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='subtotal',
            field=models.FloatField(verbose_name='Toplam'),
        ),
    ]
