# Generated by Django 4.2.7 on 2023-12-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_total_alter_orderproduct_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Accepted', 'İşleme Alındı'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], default='Yeni', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Accepted', 'İşleme Alındı'), ('Preparing', 'Hazırlanıyor'), ('OnShipping', 'Kargolandı'), ('Completed', 'Tamamlandı'), ('Canceled', 'İptal Edildi')], default='Yeni', max_length=10, verbose_name='Durum'),
        ),
    ]
